name: "Setup"
runs:
  using: "composite" # <-- this is the important part
  steps:

    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip' # caching pip dependencies

    - name: Install dependencies
      shell: bash
      run: python -m pip install numpy intelhex

    - name: Install dependencies
      shell: bash
      run: sudo apt install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential libstdc++-arm-none-eabi-newlib

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
