name: Build

on:
  pull_request:
    branches: [ "github_build" ]
  workflow_dispatch:
      inputs:
      version:
        description: 'FMW version'
        required: true
        type: string

env:
  FIRMWARE_VERSION: ${{ github.event.inputs.version }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and submodules with token
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

#      - name: Install dependencies
#        run: sudo apt install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential libstdc++-arm-none-eabi-newlib

      - uses: ./.github/actions/setup

      - name: Build
        run: cd build; make release

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Compilation
          path: build/release/Wireless_neuron_final.hex
