name: Build

on:
  pull_request:
    branches: [ "github_build" ]
  workflow_dispatch:
      inputs:
      version:
        description: 'FMW version'
        required: true
        type: string

env:
  FIRMWARE_VERSION: ${{ github.event.inputs.version }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          
      # - name: Get Nordic SDK
          # run: mkdir -p libraries/SDK
            # wget https://nsscprodmedia.blob.core.windows.net/prod/software-and-other-downloads/sdks/nrf5/binaries/nrf5_sdk_17.1.0_ddde560.zip
            # unzip nrf5_sdk_17.1.0_ddde560.zip -d libraries/SDK

      - uses: ./.github/actions/setup

      - name: Build
        run: cd build; make -j4 release

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Compilation
          path: build/release/Wireless_neuron_final.hex
